### ISSUE TITLE
Suggest adding support for Thread2Matter (Thread-to-Matter, formerly Project CHIP) as a gateway/bridge

### ISSUE THREAD

**Issue by Hedda** [vke/thread2mqtt#5]
@vke What do you think about suggestion idea of adding support for Thread2Matter (Thread-to-Matter, formerly Project CHIP)?

The goal would be to have something like a Thread-to-Matter gateway/bridge for non-native Matter devices.

The rationale is that the new Matter/CHIP standard will practically replace Thread (or at least abstract away Thread application layer as Thread will only be used as a networking layer) so the primary use case will be to have Thread-to-Matter gateways/bridges which allow users to integrate their "legacy" Thread devices with a Matter/CHIP network without having to upgrade the firmware on those Thread devices with a new application firmware that is natively compatible with Matter/CHIP.

That is, a gateway/bridge software that enables users to integrate standard OpenThread devices into a Matter/CHIP network.

More info on new Matter/CHIP standard in this somewhat related Zigbee2Matter discussion here by Zigbee2MQTT community:
https://github.com/Koenkk/zigbee2mqtt/discussions/7443

Home Assistant community users also has a somewhat relative features  request discussion as well here:

https://community.home-assistant.io/t/thread-matter-support/305633

**Comment by vke** [comment]
@Hedda Sorry, this project is a simple wrapper for my own (custom) protocol over my Thread network. This project is not related to Matter/CHIP.
